# SPDX-FileCopyrightText: 2025 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

build:
    environment:
        php: "8.1"

filter:
    excluded_paths:
        - '.github/*'
        - 'appinfo/info.xml'
        - 'build/*'
        - 'composer/*'
        - 'css/*'
        - 'doc/*'
        - 'img/*'
        - 'l10n/*'
        - 'LICENSES/*'
        - 'src/*'
        - 'templates/*'
        - 'tests/*'
        - 'vendor/*'
        - 'vendor-bin/*'

imports:
    - php

tools:
    external_code_coverage:
        timeout: 1000
