<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\TwoFactorGateway\Notification;

use OCA\TwoFactorGateway\AppInfo\Application;
use OCP\IURLGenerator;
use OCP\L10N\IFactory;
use OCP\Notification\INotification;
use OCP\Notification\INotifier;
use OCP\Notification\UnknownNotificationException;
use Override;
use Psr\Log\LoggerInterface;

class Notifier implements INotifier {
	public function __construct(
		private IFactory $factory,
		private IURLGenerator $url,
		private LoggerInterface $logger,
	) {
	}

	#[Override]
	public function getID(): string {
		return Application::APP_ID;
	}

	#[Override]
	public function getName(): string {
		return $this->factory->get(Application::APP_ID)->t('Two-Factor Gateway');
	}

	#[Override]
	public function prepare(INotification $notification, string $languageCode): INotification {
		if ($notification->getApp() !== Application::APP_ID) {
			throw new UnknownNotificationException();
		}

		$l = $this->factory->get(Application::APP_ID, $languageCode);

		if ($notification->getSubject() === 'whatsapp_auth_error') {
			$this->logger->debug('Preparing WhatsApp auth error notification for user ' . $notification->getUser());
			return $this->parseWhatsAppAuthError($notification, $l);
		}

		if ($notification->getSubject() === 'whatsapp_session_warning') {
			$this->logger->debug('Preparing WhatsApp session warning notification for user ' . $notification->getUser());
			return $this->parseWhatsAppSessionWarning($notification, $l);
		}

		$this->logger->warning('Unknown notification subject: ' . $notification->getSubject());
		throw new UnknownNotificationException();
	}

	private function parseWhatsAppAuthError(INotification $notification, \OCP\IL10N $l): INotification {
		$notification
			// TRANSLATORS Notification subject shown to admins when the GoWhatsApp API credentials/session are invalid.
			->setParsedSubject($l->t('Two-Factor Gateway: WhatsApp authentication failed'))
			// TRANSLATORS Admin notification body. Keep `occ twofactorauth:gateway:configure gowhatsapp` unchanged because it is a command.
			->setParsedMessage($l->t('Two-Factor Gateway cannot send WhatsApp verification codes until this is fixed. Reconfigure the GoWhatsApp gateway from the command line using: occ twofactorauth:gateway:configure gowhatsapp'))
			->setIcon($this->url->getAbsoluteURL($this->url->imagePath('core', 'actions/error.svg')))
			->setLink($this->url->linkToRouteAbsolute('settings.AdminSettings.index', ['section' => 'overview']));

		return $notification;
	}

	private function parseWhatsAppSessionWarning(INotification $notification, \OCP\IL10N $l): INotification {
		$params = $notification->getSubjectParameters();
		$reason = $params['reason'] ?? '';

		$notification
			// TRANSLATORS Notification subject shown to admins when session health score indicates instability.
			->setParsedSubject($l->t('Two-Factor Gateway: WhatsApp session is unstable'))
			->setParsedMessage(
				// TRANSLATORS %s contains a pre-formatted technical reason generated by the monitor (risk score + observed states).
				$reason !== ''
					? $l->t('WhatsApp session warning: %s', [$reason])
					// TRANSLATORS Admin notification body for instability without detailed reason payload.
					: $l->t('The WhatsApp session is unstable and may require re-authentication soon. Monitor the session and reconfigure the GoWhatsApp gateway if needed.')
			)
			->setIcon($this->url->getAbsoluteURL($this->url->imagePath('core', 'actions/warning.svg')))
			->setLink($this->url->linkToRouteAbsolute('settings.AdminSettings.index', ['section' => 'overview']));

		return $notification;
	}
}
